docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
site_name: oneplace-event
site_description: "onePlace Faucet Batch"
repo_url: 'https://github.com/OnePlc/PLC_X_Faucet_Batch'
theme: bootstrap4
extra:
  project: onePlc